---
title: "Nonlinearity"
author: "Yizhou Zhang"
date: "June 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(statar)
library(mgcv)
library(caret)
library(rdd)
library(ggplot2)
library(statar)
library(dplyr)
library(glmnet)
library(miceadds)
library(multiwayvcov)
library(broom)
library(stargazer)
library(plm)
library(visreg)
```

## read data



```{r cars}


Intst95 =read.csv("C:/Users/NAOYA/Box Sync/My Research/Tax diff on Migration/Rstudio/Int95.csv")
Intst99 =read.csv("C:/Users/NAOYA/Box Sync/My Research/Tax diff on Migration/Rstudio/Int99.csv")

Intst95 = subset(Intst95, log_oddsratio95 != 0)

```


## baseline regression 

Replication of Moretti & Wilson 2017, table 2a, column (6) 



```{r}
load("C:/Users/NAOYA/Box Sync/My Research/Tax diff on Migration/models/Baseline")
```



```{r}
tab.clu = lm.cluster(
  data = Intst95,
  log_oddsratio95 ~ ATR_p99_diff_log +  cit_state_diff_log + itc_state_diff_log
  + state_cred_diff_log
  + as.factor(year)
  + as.factor(pairIDasymmetric) + as.factor(regpairyear),
  cluster = "clustall"
  )
  
write.csv(summary(tab.clu), file = "C:/Users/NAOYA/Box Sync/My Research/Tax diff on Migration/models/Baseline.csv")
  
```



## Summary Statistics 

first demean the tax variables 

```{r}



d_mean = transform(Intst95, 
    d_atr = ATR_p99_diff_log-ave(ATR_p99_diff_log, year)-ave(ATR_p99_diff_log, pairIDasymmetric),
    d_cit = cit_state_diff_log-ave(cit_state_diff_log, year)-ave(cit_state_diff_log, pairIDasymmetric),
    d_itc = itc_state_diff_log-ave(itc_state_diff_log, year)-ave(itc_state_diff_log, pairIDasymmetric),
    d_cred = state_cred_diff_log-ave(state_cred_diff_log, year)-ave(state_cred_diff_log, pairIDasymmetric),
    d_logodd =  log_oddsratio95-ave(log_oddsratio95, year)-ave(log_oddsratio95, pairIDasymmetric)
)



```


binscatter plot 

```{r}
ggplot(d_mean, aes(y = d_logodd , x = d_atr)) + stat_binmean(n = 50) + xlab("Log Top Individual Net-of-ATR Rate") +
                                                            ylab("Outmigration log odds-ratio") + geom_smooth(method = "lm",
                                                            formula = y ~ splines::bs(x, 3),
                                                            se = TRUE)+ xlim(-0.05, 0.05)
                                                            

ggplot(d_mean, aes(y = d_logodd , x = d_cit)) + stat_binmean(n = 80) + xlab("Log Corporate Net-of-CIT Rate") +
                                                            ylab("Outmigration log odds-ratio") + geom_smooth(method = "lm",
                                                            formula = y ~ splines::bs(x, 3),
                                                            se = TRUE)+ xlim(-0.05, 0.05)


                                                            
ggplot(d_mean, aes(y = d_logodd , x = d_itc)) + stat_binmean(n = 80) + xlab("Log Investment Tax Credits") +
                                                            ylab("Outmigration log odds-ratio") + geom_smooth(method = "lm",
                                                            formula = y ~ splines::bs(x, 3),
                                                            se = TRUE)+ xlim(-0.06, 0.06)
                                                            

ggplot(d_mean, aes(y = d_logodd , x = d_cred)) + stat_binmean(n = 80) + xlab("Log R & D tax credits") +
                                                            ylab("Outmigration log odds-ratio") + geom_smooth(method = "lm",
                                                            formula = y ~ splines::bs(x, 3),
                                                            se = TRUE)+ xlim(-0.15, 0.15)
                                                            







ggplot(d_mean, aes(y = d_logodd , x = d_cit)) + geom_smooth(method = "lm", se= TRUE) + stat_binmean(n = 80) + xlab("Log Top Individual Net-of-CIT Rate") + ylab("Outmigration log odds-ratio") +xlim(-0.05, 0.05)




ggplot(d_mean, aes(y = d_logodd , x = d_itc)) + geom_smooth(method = "auto", se= TRUE) + stat_binmean(n = 80) + xlab("Log Top Individual Net-of-CIT Rate") + ylab("Outmigration log odds-ratio") + xlim(-0.05, 0.05)





ggplot(d_mean, aes(y = d_logodd , x = d_cred))  + stat_binmean(n = 80) + xlab("Log Top Individual Net-of-CIT Rate") +
ylab("Outmigration log odds-ratio") + geom_smooth(method = "auto", se= TRUE) +xlim(-0.15, 0.15)



g_cit = ggplot(d_mean, aes(y = d_logodd , x = d_cit)) 
g_cit + stat_binmean(n = 80) +xlab("Log Corporate Net-of-CIT Rate") +ylab("Outmigration log odds-ratio")



g_itc = ggplot(d_mean, aes(y = d_logodd , x = d_itc)) 
g_itc + stat_binmean(n = 80) +xlab("Log Investment Tax Credits") +ylab("Outmigration log odds-ratio")



g_cred = ggplot(d_mean, aes(y = d_logodd , x = d_cred)) 
g_cred + stat_binmean(n =80) +xlab("Log R & D tax credits") +ylab("Outmigration log odds-ratio")


```


## Spline regression 


```{r}
load("C:/Users/NAOYA/Box Sync/My Research/Tax diff on Migration/models/splineall.rda")
```



```{r pressure, echo=FALSE}

fit.sall = mgcv::gam (
log_oddsratio95 ~ s(ATR_p99_diff_log) +  s(cit_state_diff_log) + s(itc_state_diff_log) + s(state_cred_diff_log) + as.factor(year)
+ as.factor(pairIDasymmetric) + as.factor(regpairyear),
data = Intst95,
method = "GCV.Cp"
)
       


#result = summary(fit.sall)





#splresult = summary(fit.sall)$s.table

       
#stargazer(splresult, type = "html", title = "Spline Regression Results", digits = NA)

   
save(fit.sall, file = "C:/Users/NAOYA/Box Sync/My Research/Tax diff on Migration/models/splineall.rda")

```




```{r}
#plot using ggplot 

plotPoints = seq(min(Intst95$ATR_p99_diff_log), max(Intst95$ATR_p99_diff_log), by = .005)

yHat = predict.gam(fit.sall, list(age = plotPoints), se.fit = TRUE)


```


## plot the spline regression 

```{r}

plot.gam(fit.sall ,select =1 , xlab="Log of net-of-tax of Personal Income Tax", ylab = "Fitted Outmigration Log-odds Ratio", lwd =1.5)
abline(v = 0.04, lty = 5)
abline(v= -0.04, lty =5)
abline(a = 0, b = 1.89, lty = 6, lwd = 1, col = "red")
text(x = 0.08, y = -0.5, "net-of-ATR Diff\n = 0.04")
text(x = -0.08, y = -0.5, "net-of-ATR Diff \n = -0.04")
text(x= 0.13, y= 0.5, "y=1.8x, \n linear elasticity")




plot.gam(fit.sall ,select =2 , xlab="Log of net-of-tax of Corporate Income Tax", ylab = "Fitted Outmigration Log-odds Ratio", lwd =1.5)
abline(a = 0, b = 1.93, lty = 6, lwd = 1, col = "red")
text(x= 0.10, y= 0.5, "y=1.9x, \n linear elasticity")


plot.gam(fit.sall ,select =3 , xlab="Log of Investment Tax Credit", ylab = "Fitted Outmigration Log-odds Ratio", lwd =1.5)
abline(v = -0.02, lty = 5)
abline(v = 0, lty = 5)
abline(a = 0, b = 1.73, lty = 6, lwd = 1, col = "red")
text(x = -0.03, y = 0.5, "ITC diff \n = -0.02")
text(x = 0.02, y = -0.5, "Zero Credit \n Difference")
text(x= 0.065, y= -0.1, "y=1.7x, \n linear elasticity")



plot.gam(fit.sall ,select =4 , xlab="Log of R and D Tax Credit", ylab = "Fitted Outmigration Log-odds Ratio", lwd =1.5)
abline(v = 0.1, lty = 5)
abline(v= -0.1, lty =5)

text(x = 0.15, y = -0.5, "R&D credit Diff\n = 0.1")
text(x = -0.15, y = -0.5, "R&D credit Diff\n = -0.1")



```



## Bin Regression to quantify the changes in marginal effects. 


```{r}

Intst95_kinx = Intst95       
Intst95_kinx[,'BigATR'] =  ifelse(Intst95_kinx$ATR_p99_diff_log >= 0.04, 1, 0) 
Intst95_kinx[,'BigATR_Int'] =  Intst95_kinx$ATR_p99_diff_log *Intst95_kinx$BigATR 

Intst95_kinx[,'lowATR'] =  ifelse(Intst95_kinx$ATR_p99_diff_log <= -0.04, 1, 0) 
Intst95_kinx[,'lowATR_Int'] =  Intst95_kinx$ATR_p99_diff_log *Intst95_kinx$lowATR 

Intst95_kinx[,'highCIT'] =  ifelse(Intst95_kinx$ATR_p99_diff_log >= 0, 1, 0) 
Intst95_kinx[,'highCIT_Int'] =  Intst95_kinx$cit_state_diff_log *Intst95_kinx$highCIT


Intst95_kinx[,'highITC'] =  ifelse(Intst95_kinx$itc_state_diff_log >= 0, 1, 0) 
Intst95_kinx[,'highITC_Int'] =  Intst95_kinx$itc_state_diff_log *Intst95_kinx$highITC 



Intst95_kinx[,'LowITC'] =  ifelse(Intst95_kinx$itc_state_diff_log <= -0.02, 1, 0) 
Intst95_kinx[,'LowITC_Int'] =  Intst95_kinx$itc_state_diff_log *Intst95_kinx$LowITC 


Intst95_kinx[,'highCRED'] =  ifelse(Intst95_kinx$state_cred_diff_log  >= 0.1, 1, 0) 
Intst95_kinx[,'highCRED_Int'] =  Intst95_kinx$state_cred_diff_log  *Intst95_kinx$highCRED

Intst95_kinx[,'LowCRED'] =  ifelse(Intst95_kinx$state_cred_diff_log  <= -0.1, 1, 0) 
Intst95_kinx[,'LowCRED_Int'] =  Intst95_kinx$state_cred_diff_log  *Intst95_kinx$LowCRED
```

#Then generate table 2

```{r}
# first replicate the baseline findings of Moretti Wilson 2017
tab.allKinx_One = lm.cluster (
  log_oddsratio95 ~ ATR_p99_diff_log
  + cit_state_diff_log 
  + itc_state_diff_log 
  + state_cred_diff_log
  + as.factor(year)
  + as.factor(pairIDasymmetric) + as.factor(regpairyear),
  data = Intst95_kinx, cluster = "clustall")

summary(tab.allKinx_One)


# then perform the interaction regression to investigate nonlinearity 
tab.allKinx_Two = lm.cluster(
  log_oddsratio95 ~ ATR_p99_diff_log  + BigATR_Int + lowATR_Int 
  + cit_state_diff_log + highCIT_Int
  + itc_state_diff_log  + highITC_Int + LowITC_Int
  + state_cred_diff_log + highCRED_Int + LowCRED_Int
  + as.factor(year)
  + as.factor(pairIDasymmetric) + as.factor(regpairyear),
  data = Intst95_kinx, cluster = "clustall")

```




```{r}

nonzero = which(coef(fit_cv) != 0)
names = coef(fit_cv)
rownames(names)[nonzero]

stargazer(
tab.allKinx_Two,
type = "text",
keep = c(
"ATR_p99_diff_log",
"BigATR_Int",
"lowATR_Int",
"cit_state_diff_log",
"highCIT_Int",
"itc_state_diff_log",
"highITC_Int",
"state_cred_diff_log" , 
"highCRED_Int" , 
"LowCRED_Int"
),

#covariate.labels = c("Gent 2010-15","Renter Dummy","MedInc","HighInc","Gent*Rent","Renter*MedInc","Renter*HighInc"),

#column.labels = c("Full", "Gentrified", "Nongentrified"),
df=FALSE ,
omit.stat = c("f", "rsq", "res.dev"), header = FALSE
)  


```



